### ISSUE TITLE
<text> tag under section from ccda file is not converted to FHIR

### ISSUE THREAD

**Issue by SanjeevS2010** [chaseastewart/fhir-converter#11]
<text> tag under section from ccda is not converted to FHIR.
we are processing Consultation_Note.ccda and we have couple of <text> tag under sections, those are not gettting converted to FHIR. We are not gettting any output for those tags.
Exmaple from Consultation_Note.ccda below:
<section>
					
					<templateId root="2.16.840.1.113883.10.20.22.2.6.1" extension="2014-06-09"/>
					<code code="48765-2" codeSystem="2.16.840.1.113883.6.1"/>
					<title>ALLERGIES AND ADVERSE REACTIONS</title>
					<text>
						<table border="1" width="100%">
							<thead>
								<tr>
									<th>Substance</th>
									<th>Reaction</th>

**Comment by chaseastewart** [comment]
Resolved.
